//! Resolve the pinned postflop-solver commit SHA at build time so the
//! strategy export can name the exact engine version it was generated by.
//!
//! Strategy:
//!   1. Try `git -C ../postflop-solver rev-parse HEAD`. This is the source
//!      of truth in the monorepo.
//!   2. If that fails (e.g. the directory was vendored without `.git`),
//!      fall back to a `SOLVER_WASM_ENGINE_SHA` env var the user can set.
//!   3. If neither works, leave the var unset and let `solver_version()`
//!      report `"unknown"`. The build still succeeds.

use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=SOLVER_WASM_ENGINE_SHA");

    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let solver_dir = manifest_dir.join("..").join("postflop-solver");
    // Re-run if HEAD moves under the pinned solver checkout.
    let head_file = solver_dir.join(".git").join("HEAD");
    if head_file.exists() {
        println!("cargo:rerun-if-changed={}", head_file.display());
    }

    if let Some(sha) = read_sha(&solver_dir).or_else(|| std::env::var("SOLVER_WASM_ENGINE_SHA").ok())
    {
        let short = sha.chars().take(12).collect::<String>();
        println!("cargo:rustc-env=SOLVER_WASM_ENGINE_SHA={short}");
    }
}

fn read_sha(solver_dir: &Path) -> Option<String> {
    let output = Command::new("git")
        .args(["rev-parse", "HEAD"])
        .current_dir(solver_dir)
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    let sha = String::from_utf8(output.stdout).ok()?.trim().to_string();
    if sha.is_empty() {
        None
    } else {
        Some(sha)
    }
}
