-- Migration 006: historical no-op retained for migration continuity
--
-- The GIN index required by find_leaks (GET /stats/leaks) was already
-- created in migration 005:
--
--   CREATE INDEX idx_llm_analyses_user_tags ON llm_analyses USING GIN (leak_tags);
--
-- This migration remains an intentional no-op so databases that already
-- recorded migration 006 stay aligned with clean installations. The MCP
-- adapter that originally motivated this file has been removed; the index
-- remains useful to the authenticated REST statistics endpoint.
--
-- If you are running against a database where 005 was applied without the
-- GIN index (e.g. an early schema), run:
--
--   CREATE INDEX IF NOT EXISTS idx_llm_analyses_user_tags
--     ON llm_analyses USING GIN (leak_tags);
--
-- The index accelerates the UNNEST(leak_tags) aggregation in compute_leaks()
-- (backend/app/stats/compute.py) which powers GET /stats/leaks.

SELECT 1; -- no-op, keeps migration runners happy
